name: Data Platform CI/CD

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make build ENV=$ENV

      - name: Deploy
        run: make deploy ENV=$ENV

      - name: Test
        run: make test ENV=$ENV

      - name: Cleanup
        run: k3d cluster delete data-platform-$ENV --yes
